 global using Toolkit.Domain.ValueObjects;
global using Toolkit.Domain.Enums;
global using Toolkit.Domain.Models;
global using Toolkit.Domain.PdfAnalysis;
global using Toolkit.Domain.BatchRenaming;
global using Toolkit.Domain.ImagePreprocessing;
global using Toolkit.Domain.Ocr;
global using Toolkit.Domain.OcrTraining;
global using Toolkit.Application.Common.Interfaces;
